version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DB_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: ./workspace
        target: /workspace

      - type: volume
        source: mongodb_data_volume
        target: /data/db
        
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "28081:8081"
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${DB_USER}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${DB_PASSWORD}"
      ME_CONFIG_MONGODB_URL: "${MONGOCONN_STRING}"
    depends_on:
      - mongo
  server:
    container_name: express-server
    build:
        context: ./server
        dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ./server
        target: /usr/src/app
    env_file:
      - .env
    environment:
      MONGOCONN_STRING: "${MONGOCONN_STRING}"
    depends_on:
        - mongo
  client:
    container_name: react-client
    build:
        context: ./client
        dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./client
        target: /usr/src/app
    depends_on:
        - server

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - server
volumes:
  mongodb_data_volume:
    driver: local    

